#' Downstream analysis based on MAGeCK-MLE result
#'
#' Integrative analysis pipeline using the gene summary table in MAGeCK MLE results
#'
#' @docType methods
#' @name FluteQC
#' @rdname FluteQC
#' @aliases fluteqc
#'
#' @param gene_summary A data frame or a file path to gene summary file generated by MAGeCK-MLE.
#' @param treatname A character vector, specifying the names of treatment samples.
#' @param ctrlname A character vector, specifying the names of control samples.
#' If there is no controls in your CRISPR screen, you can specify "Depmap" as ctrlname and set `incorporateDepmap=TRUE`.
#' @param lab_treat A character, for labelling the treatment condition on graphs.
#' @param lab_ctrl A character, for labelling the control condition on graphs.
#' @param keytype "Entrez" or "Symbol".
#' @param organism "hsa" or "mmu".
#' @param incorporateDepmap Boolean, indicating whether incorporate Depmap data into analysis.
#' @param cell_lines A character vector, specifying the cell lines in Depmap to be considered.
#' @param lineages A character vector, specifying the lineages in Depmap to be considered.
#' @param norm_method One of "none", "cell_cycle" (default) or "loess".
#' @param posControl A character vector, specifying a list of positive control gene symbols.
#' @param EG A character vector of symbols of common essential genes to be omitted. 
#' If `Null` (default), common essential genes built into MAGeCKFlute package will be used.
#' @param proj A character, indicating the prefix of output file name, which can't contain special characters.
#' @param width The width of summary pdf in inches.
#' @param height The height of summary pdf in inches.
#' @param figwidth The width of png figures.
#' @param units The units of png figure sizes, one of "in", "cm", "mm", "px".
#' @param dpi dpi of png figures, default = 1200.
#' @param outdir Output directory on disk.
#' @param verbose Boolean
#'
#' @author Wubing Zhang
#'
#' @return All of the pipeline results is output into the \code{out.dir}/MAGeCKFlute_\code{proj},
#' which includes a pdf file and many folders. The pdf file 'FluteMLE_\code{proj}_\code{norm_method}.pdf' is the
#' summary of pipeline results. For each section in this pipeline, figures and useful data are
#' outputed to corresponding subfolders.
#' \itemize{
#'   \item {QC}: {Quality control}
#'   \item {Selection}: {Positive selection and negative selection.}
#'   \item {Enrichment}: {Enrichment analysis for positive and negative selection genes.}
#'   \item {PathwayView}: {Pathway view for top enriched pathways.}
#' }
#'
#' @details MAGeCK-MLE can be used to analyze screen data from multi-conditioned experiments. MAGeCK-MLE
#' also normalizes the data across multiple samples, making them comparable to each other. The most important
#' ouput of MAGeCK MLE is `gene_summary` file, which includes the beta scores of multiple conditions and
#' the associated statistics. The `beta score`  for each gene describes how the gene is selected: a positive
#' beta score indicates a positive selection, and a negative beta score indicates a negative selection.
#'
#' The downstream analysis includes identifying essential, non-essential, and target-associated genes,
#' and performing biological functional category analysis and pathway enrichment analysis of these genes.
#' The function also visualizes genes in the context of pathways to benefit users exploring screening data.
#'
#'
#' @seealso \code{\link{FluteRRA}}
#'
#' @examples
#' file3 = file.path(system.file("extdata", package = "MAGeCKFlute"),
#' "testdata/mle.gene_summary.txt")
#' \dontrun{
#'   # functional analysis for MAGeCK MLE results
#'   FluteMLE(file3, treatname = "Pmel1", ctrlname = "Pmel1_Ctrl", proj = "Pmel1")
#' }
#'
#' @import dplyr ggplot2 stats grDevices utils gridExtra grid
#' @export

FluteQC <- function(gene_summary, data_type = "chronos", treatname, ctrlname = "Depmap",
                     lab_treat = "Treatment", lab_ctrl = "Control",
                     keytype = "Symbol", organism = "hsa", # Input dataset
                     incorporateDepmap = FALSE,
                     cell_lines = NA, lineages = "All",
                     norm_method = "cell_cycle", posControl = NULL,
                     EG = NULL,
                     proj = NA,
                     width = 10, height = 7,  figwidth = 13.5, units = "cm",  dpi = 1200, 
                     outdir = ".", verbose = TRUE){
  ## Prepare the running environment ##
  {
    message(Sys.time(), " # Create output dir and pdf file...")
    outdir = file.path(outdir, paste0("MAGeCKFlute_", proj))
    dir.create(file.path(outdir), showWarnings = FALSE, recursive = T)
    output_pdf = paste0("FluteQC_", proj, ".pdf")
    pdf(file.path(outdir, output_pdf), width = width, height = height)
  }
  
  ## Beta Score Preparation ##
  {
    if (data_type == "mle") {
      beta = ReadBeta(gene_summary)
    } else if (data_type == "chronos") {
      beta = gene_summary
    }
    
    if(tolower(keytype)!="entrez"){
      beta$EntrezID = TransGeneID(beta$Gene, keytype, "Entrez", organism = organism)
    }else{
      beta$EntrezID = beta$Gene
    }
    if(tolower(keytype)!="symbol"){
      beta$Symbol = TransGeneID(beta$Gene, keytype, "Symbol", organism = organism)
    }else{
      beta$Symbol = beta$Gene
    }
    if(organism != "hsa"){
      beta$HumanGene = TransGeneID(beta$Symbol, "Symbol", "Symbol",
                                   fromOrg = organism, toOrg = "hsa")
      beta$GeneID = TransGeneID(beta$HumanGene, "Symbol", "Entrez")
    }else{
      beta$HumanGene = beta$Symbol
      beta$GeneID = beta$EntrezID
    }
    
    message(Sys.time(), " # Transform id to official human gene name ...")
    idx1 = is.na(beta$EntrezID)
    idx2 = !is.na(beta$EntrezID) & duplicated(beta$EntrezID)
    idx = idx1|idx2
    if(sum(idx1)>0) message(sum(idx1), " genes fail to convert into Entrez IDs: ",
                            paste0(beta$Gene[idx1], collapse = ", "))
    if(sum(idx2)>0) message(sum(idx2), " genes have duplicate Entrez IDs: ",
                            paste0(beta$Gene[idx2], collapse = ", "))
    
    dd = beta[!idx, ]
    if(incorporateDepmap | "Depmap"%in%ctrlname)
      dd = IncorporateDepmap(dd, symbol = "HumanGene", cell_lines = cell_lines,
                             lineages = lineages)
    if(!all(c(ctrlname, treatname) %in% colnames(dd)))
      stop("Sample name doesn't match !!!")
    
    if (data_type == "mle") {
    ## Normalization
    if(tolower(norm_method)=="cell_cycle")
      dd = NormalizeBeta(dd, id = "HumanGene", samples = c(ctrlname, treatname),
                         method = "cell_cycle", posControl = posControl) %>% as.data.frame()
    if(tolower(norm_method)=="loess")
      dd = NormalizeBeta(dd, id = "HumanGene", samples = c(ctrlname, treatname), method = "loess") %>% as.data.frame()
    }
  }
  ## Distribution of beta scores ##
  {
    ## All genes ##
    outputDir1 = file.path(outdir, paste0("Figures"))
    dir.create(outputDir1, showWarnings = FALSE)
    idx_distr = c(ctrlname, treatname)
    if (length(idx_distr) <= 4) {
      P1 = ViolinView(dd[, idx_distr], ylab = "Gene effect score", main = "All genes") + ylim(-3.5,1.5)
      ggsave(paste0(outputDir1,"/", "ViolinView_all.png"), 
             P1,
             width = figwidth, height = figwidth*3/4, units = units, dpi = dpi)
    } else  {
      message(Sys.time(), " # >4 reps to be graphed in ViolinView, figure will be double specified width")
      P1 = ViolinView(dd[, idx_distr], ylab = "Gene effect score", main = "All genes") +
        theme(axis.text.x = element_blank()) + ylim(-3.5,1.5)
      ggsave(paste0(outputDir1,"/", "ViolinView_all.png"), 
             P1 + theme(legend.position = "right"),
             width = figwidth*4/3, height = figwidth*3/4, units = units, dpi = dpi)
    }
    # P1 = ViolinView(dd[, idx_distr], ylab = "Gene effect score", main = "All genes",
    #                 filename = paste0(outputDir1,"/", "ViolinView_all.png"))
    P2 = DensityView(dd[, idx_distr], xlab = "Gene effect score", main = "All genes") + xlim(-3.5,1.5)
    P3 = ConsistencyView(dd, ctrlname, treatname, lab_ctrl = lab_ctrl, lab_treat = lab_treat, main = "All genes") + 
      ylim(-3.5,1.5) + xlim(-3.5,1.5)
    P4 = MAView(dd, ctrlname, treatname, main = "All genes", xlim = c(-3.5,1.5), ylim = c(-1.5,1.5))
    gridExtra::grid.arrange(P1, P2, P3, P4, ncol = 2)
    
    ggsave(filename = paste0(outputDir1, "/", "DensityView_all.png"),
           P2,
           width = figwidth, height = figwidth*3/4, units = units, dpi = dpi)
    ggsave(filename = paste0(outputDir1, "/", "Consistency_all.png"),
           P3,
           width = figwidth, height = figwidth*3/4, units = units, dpi = dpi)
    ggsave(filename = paste0(outputDir1, "/", "MAView_all.png"),
           P4,
           width = figwidth, height = figwidth*3/4, units = units, dpi = dpi)
    
    
    ## Essential genes ##
    Zuber_Essential = readRDS(file.path(system.file("extdata", package = "MAGeCKFlute"),
                                        "Zuber_Essential.rds"))
    if(is.null(EG))
      idx = toupper(dd$HumanGene) %in% toupper(Zuber_Essential$GeneSymbol)
    else
      idx = toupper(dd$Gene) %in% toupper(EG)
    
    if(sum(idx) > 10){
      if (length(idx_distr) <= 4) {
        P1 = ViolinView(dd[idx, idx_distr], ylab = "Gene effect score", main = "Essential genes") + ylim(-3.5,1.5)
        ggsave(paste0(outputDir1,"/", "ViolinView_posctrl.png"), 
               P1,
               width = figwidth, height = figwidth*3/4, units = units, dpi = dpi)
      } else  {
        message(Sys.time(), " # >4 reps to be graphed in ViolinView, figure will be double specified width")
        P1 = ViolinView(dd[idx, idx_distr], ylab = "Gene effect score", main = "Essential genes") +
          theme(axis.text.x = element_blank()) + ylim(-3.5,1.5)
        ggsave(paste0(outputDir1,"/", "ViolinView_posctrl.png"), 
               P1 + theme(legend.position = "right"),
               width = figwidth*4/3, height = figwidth*3/4, units = units, dpi = dpi)
      }
      # P1 = ViolinView(dd[, idx_distr], ylab = "Gene effect score", main = "Essential genes",
      #                 filename = paste0(outputDir1,"/", "ViolinView_posctrl.png"))
      P2 = DensityView(dd[idx, idx_distr], xlab = "Gene effect score", main = "Essential genes") + xlim(-3.5,1.5)
      P3 = ConsistencyView(dd[idx, ], ctrlname, treatname, lab_ctrl = lab_ctrl, lab_treat = lab_treat, main = "Essential genes") + 
        ylim(-3.5,1.5) + xlim(-3.5,1.5)
      P4 = MAView(dd[idx, ], ctrlname, treatname, main = "Essential genes", xlim = c(-3.5,1.5), ylim = c(-1.5,1.5))
      gridExtra::grid.arrange(P1, P2, P3, P4, ncol = 2)
      
      ggsave(filename = paste0(outputDir1, "/", "DensityView_posctrl.png"),
             P2,
             width = figwidth, height = figwidth*3/4, units = units, dpi = dpi)
      ggsave(filename = paste0(outputDir1, "/", "Consistency_posctrl.png"),
             P3,
             width = figwidth, height = figwidth*3/4, units = units, dpi = dpi)
      ggsave(filename = paste0(outputDir1, "/", "MAView_posctrl.png"),
             P4,
             width = figwidth, height = figwidth*3/4, units = units, dpi = dpi)
      
    }
  }
  dev.off()
}